[default]
host = Win11

[WinEventLog://Security]
disabled = 0
index = main

[WinEventLog://System]
disabled = 0
index = main

[WinEventLog://Application]
disabled = 0
index = main

[WinEventLog://Microsoft-Windows-Sysmon/Operational]
disabled = 0
index = main

[WinEventLog://Microsoft-Windows-PowerShell/Operational]
disabled = 0
index = main

[monitor://$WINDIR\system32\LogFiles\Firewall\pfirewall.log]
disabled = false
sourcetype = windows firewall
index = main